# config/meta.yml

meta_product_name: "Preszle"
meta_title: "Preszle - The news at your fingertips, served in pretzel sized portions"
meta_description: "Relevant description"
meta_image: "preszle_image.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
